POST http://localhost:3000/auth/login
Content-Type: application/json

{
"username": "email@jfdev.de",
  "password": "12345678"
}

> {%
client.global.set("auth_token", response.body.accessToken);
%}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "displayedName": "Jonas",
  "email": "email@jfdev.de",
  "plainPassword": "12345678"
}

###

GET http://localhost:3000/challenge/1f9bd6af-02bd-4eea-aea1-4e18bac26040
Authorization: Bearer {{auth_token}}

###
